### Error in:   0:0:Construir Mapa 01
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:1:Construir Mapa 02
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:2:Construir Mapa 03
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:3:Construir Mapa 04
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:4:Construir Mapa 05
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:5:Construir Mapa 06
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:6:Construir Mapa 07
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:7:Construir Mapa 08
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:8:Construir Mapa 09
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:9:Construir Mapa 10
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:10:Construir Mapa 11
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:11:Construir Mapa 12
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:12:Construir Mapa 13
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:13:Construir Mapa 14
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:28:Identidade Mapa 01
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:29:Identidade Mapa 02
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:30:Identidade Mapa 03
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:31:Identidade Mapa 04
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:32:Identidade Mapa 05
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:33:Identidade Mapa 06
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:34:Identidade Mapa 07
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:35:Identidade Mapa 08
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:36:Identidade Mapa 09
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:37:Identidade Mapa 10
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:38:Identidade Mapa 11
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:39:Identidade Mapa 12
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:40:Identidade Mapa 13
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
### Error in:   0:41:Identidade Mapa 14
<<timeout>>
CallStack (from HasCallStack):
  error, called at tests/Fase1.hs:27:29 in main:Main
Cases: 42  Tried: 42  Errors: 28  Failures: 0
